<?php

use Drupal\Core\Access\AccessResult;

/**
 * Implements hook_node_access().
 */
 function content_restrict_node_access($node, $op, $account) {

  if ($account->hasRole('content editor')) {
    return AccessResult::allowed();
  }

  if ($account->isAnonymous() && $account->hasRole('student')) {

      if (user_is_registered_for_node($account, $node)) {
        return AccessResult::allowed();
      } else {
        return AccessResult::forbidden()->addCacheableDependency($node);
  }
  return AccessResult::forbidden();
  }

}

function user_is_registered_for_node($account, $node) {
  if ($node->hasField('field_user')) {
    $field_registered_users = $node->get('field_user')->referencedEntities();

    foreach ($field_registered_users as $registered_user) {
      if ($registered_user->id() == $account->id()) {
        return true;
      }
    }
  }

  return false;
}

